name: Agron 590RD @ ISU
description: A course in data stewardship for earth systems scientists at Iowa State University.
url: http://localhost:4000
markdown: kramdown
permalink: /:year/:month/:day/:title
navigation:
- text: Home
  url: /index.html
- text: Syllabus
  url: /syllabus.html
- text: Help
  url: /help.html
- text: People
  url: /people.html
- text: Blog
  url: /blog.html
  layout: post